export const config = {
  developer: {
    name: "Nico",
    fullName: "Nicolò Celentano",
    title: "Computer Engineering Student",
    description:
      "Building AI products and automation systems.",
  },
  social: {
    github: "https://github.com/therealthund3rr",
    email: "t.thund3rr@gmail.com",
    linkedin: "https://www.linkedin.com/in/nicol%C3%B2-celentano-7677413a4/",
    instagram: "https://www.instagram.com/nico.celentano_/",
  },
  about: {
    title: "About Me",
    description:
      "I'm a Computer Engineering student based in Turin, focused on building software that solves real problems.\n\nMy work spans AI applications, automation systems, web platforms and mobile products. I enjoy taking projects from concept to deployment, combining engineering, design and product thinking into a single workflow.\n\nBeyond software development, my background in content creation and visual design influences how I approach user experience, interfaces and communication. I care as much about how a product feels as how it works.\n\nCurrently, I'm exploring AI agents, workflow automation, modern web technologies and scalable product development while continuing my engineering studies.",
  },
  career: [
    {
      period: "Now",
      title: "Computer Engineering",
      company: "Politecnico di Torino",
      desc: "Learning algorithms, systems, and math at Politecnico di Torino. Everything I build now has cleaner architecture because of it.",
      type: "study" as const,
      bar: 65,
    },
    {
      period: "2026",
      title: "Mobile App Development",
      company: "Life OS — Personal Project",
      desc: "Wanted one app to track decisions, habits, and goals with real AI context — not just a todo list. Built mobile with React Native, Expo, and Supabase real-time. Ships to phone and runs daily.",
      type: "project" as const,
      bar: 85,
    },
    {
      period: "2026",
      title: "Web Development & APIs",
      company: "Command Center — Personal Project",
      desc: "Needed a dashboard for the Life OS ecosystem without the overhead of a heavy framework. Built with Alpine.js and vanilla JS — handles live finance data, SVG charts from scratch, localStorage state. No React, no build step.",
      type: "project" as const,
      bar: 78,
    },
    {
      period: "2025–26",
      title: "Node.js & Automation",
      company: "Bots & Automations",
      desc: "Needed WhatsApp automation that runs 24/7 without cloud costs. Node.js bots on Windows Task Scheduler — fixed async timing, shutdown sequencing, API edge cases. Running at home, never fails silently.",
      type: "project" as const,
      bar: 70,
    },
    {
      period: "pre",
      title: "Video & Content Production",
      company: "Freelance",
      desc: "Years of video editing, YouTube production, and visual storytelling before touching code. This is where the design eye comes from. Still informs every color, spacing, and animation decision.",
      type: "background" as const,
      bar: 60,
    },
  ],
  techStack: [
    { symbol: "Cc", name: "Claude Code", color: "#ff6b35", number: 1 },
    { symbol: "Re", name: "React", color: "#61dafb", number: 2 },
    { symbol: "Rn", name: "React Native", color: "#61dafb", number: 3 },
    { symbol: "Ts", name: "TypeScript", color: "#3178c6", number: 4 },
    { symbol: "Tj", name: "Three.js", color: "#ffffff", number: 5 },
    { symbol: "Gs", name: "GSAP", color: "#88ce02", number: 6 },
    { symbol: "Nj", name: "Node.js", color: "#339933", number: 7 },
    { symbol: "Py", name: "Python", color: "#ffd343", number: 8 },
    { symbol: "Sb", name: "Supabase", color: "#3ecf8e", number: 9 },
    { symbol: "Al", name: "Alpine.js", color: "#77c1d2", number: 10 },
    { symbol: "Js", name: "JavaScript", color: "#f7df1e", number: 11 },
    { symbol: "Vi", name: "Vite", color: "#646cff", number: 12 },
    { symbol: "Pe", name: "Prompt Eng.", color: "#0055ff", number: 13 },
    { symbol: "Ux", name: "UI/UX Design", color: "#ff61d2", number: 14 },
    { symbol: "Gh", name: "Git / GitHub", color: "#f05032", number: 15 },
    { symbol: "Ws", name: "WhatsApp Auto", color: "#25d366", number: 16 },
    { symbol: "Gp", name: "ChatGPT", color: "#74aa9c", number: 17 },
    { symbol: "Cu", name: "Cursor", color: "#ffffff", number: 18 },
    { symbol: "Ps", name: "Photoshop", color: "#31a8ff", number: 19 },
    { symbol: "Pr", name: "Premiere", color: "#9999ff", number: 20 },
  ],
  work: [
    {
      title: "Life OS",
      tech: "React Native · Expo · Supabase · Claude API",
      desc: "One app to track decisions, habits, and goals with AI context. Running daily on my phone.",
      descLong: "Life OS is my personal AI-powered decision engine — a React Native mobile app built to track decisions, habits, goals, and context in one place. The core challenge was building smooth native animations with Lenis on mobile while keeping Supabase real-time sync fast enough to feel instant. The AI layer uses the Claude API to surface context-aware recommendations based on your history. Currently in active development — the foundation is solid and running daily on my phone.",
      status: "wip" as const,
      gradient: ["#1e3a8a", "#2563eb"] as [string, string],
      logo: "/logo-lifeos.svg",
      screenshots: ["/screen-lifeos.jpg", "/screen-lifeos-2.jpg", "/screen-lifeos-3.jpg", "/screen-lifeos-4.jpg", "/screen-lifeos-5.jpg"],
    },
    {
      title: "Command Center",
      tech: "Alpine.js · Supabase · Vanilla JS",
      desc: "Dashboard for the Life OS ecosystem — finance data, habits, goals in one view. Built without frameworks to keep it fast and maintainable.",
      descLong: "Command Center is the desktop dashboard for the Life OS ecosystem — a SaaS-style interface built entirely with Alpine.js and vanilla JS, no build step required. It integrates live finance APIs, tracks study goals and habits, and visualizes everything through custom SVG charts built from scratch. The challenge was making a premium-feeling dashboard without React's overhead — solved with Alpine's reactivity model and careful DOM manipulation.",
      status: "completed" as const,
      gradient: ["#1e1b4b", "#3730a3"] as [string, string],
      logo: "/logo-commandcenter-new.png",
      logoPosition: "23% 44%",
      logoSize: "720%",
      screenshots: ["/screen-commandcenter.png"],
    },
    {
      title: "Portfolio",
      tech: "React · Three.js · GSAP · Vite",
      desc: "This site. 3D character in WebGL, scroll-driven animations, custom cursor. Built to show the kind of work I do.",
      descLong: "This site. Built to showcase the kind of work I do — 3D character in WebGL with mouse-reactive lighting, scroll-driven animations throughout, custom cursor with mix-blend-mode, and a loading sequence that feels cinematic. The stack is Vite + React + TypeScript + Three.js + GSAP. The GLB model is 47MB committed directly to git. Deployed on Vercel with auto-deploy on every push.",
      status: "completed" as const,
      gradient: ["#0f172a", "#334155"] as [string, string],
      logo: "/logo-portfolio-new.png",
      logoPosition: "99% 44%",
      logoSize: "700%",
      screenshots: ["/portfolio-preview.png"],
    },
    {
      title: "Jarvis",
      tech: "Claude API · Node.js · MCP",
      desc: "Personal AI assistant with MCP tools and workflow automation. Active development — memory persistence and tool chaining in progress.",
      descLong: "Jarvis is my personal AI assistant — a Node.js agent with MCP (Model Context Protocol) integration that lets it use real tools: file system, browser, APIs, and custom automations. The goal is a system that knows my workflow and can execute multi-step tasks autonomously. Currently working on memory persistence across sessions and reliable tool chaining — the hard part is making it act, not just respond.",
      status: "wip" as const,
      gradient: ["#1c1917", "#7c2d12"] as [string, string],
      logo: "/logo-jarvis-new.png",
      logoPosition: "42% 46%",
      logoSize: "720%",
      screenshots: ["/screen-jarvis.png"],
    },
    {
      title: "Magic Garden Bot",
      tech: "Node.js · WhatsApp (open-wa)",
      desc: "WhatsApp bot that monitors a mobile game shop and notifies when specific items appear. Runs 24/7 on a home machine.",
      descLong: "A Node.js WhatsApp bot that monitors the in-game shop of Magic Garden — a mobile game — and sends real-time notifications when specific items appear. Polls the game's API every 30 seconds, filters items by a per-shop watchlist, and handles anti-spam tracking so you only get notified on new appearances. Also watches weather events inside the game. Built with open-wa, runs 24/7 on Windows Task Scheduler.",
      status: "completed" as const,
      gradient: ["#052e16", "#166534"] as [string, string],
      logo: "/logo-magicgarden-new.png",
      logoPosition: "61% 45%",
      logoSize: "720%",
      screenshots: ["/screen-magicgarden.jpg"],
    },
    {
      title: "Waste Bot",
      tech: "Node.js · WhatsApp (open-wa)",
      desc: "WhatsApp bot that tells the family when to take out which recycling. Runs 24/7 on a home machine, no cloud required.",
      descLong: "A WhatsApp bot for the family — sends a message every week reminding who needs to take out which specific type of recycling. Runs continuously on a home machine via Windows Task Scheduler. The tricky parts: coordinating async WhatsApp message timing (3s delay to avoid API rate limits) and clean shutdown sequencing so the Task Scheduler stop signal doesn't corrupt session state.",
      status: "shipped" as const,
      gradient: ["#022c22", "#14532d"] as [string, string],
      logo: "/logo-wastebot-new.png",
      logoPosition: "80% 45%",
      logoSize: "720%",
      screenshots: ["/screen-wastebot.png"],
    },
  ],
  allowedDomains: ["localhost", "127.0.0.1", "therealthund3rr.github.io"],
};
