export const config = {
  developer: {
    name: "Nico",
    fullName: "Nicolò Celentano",
    title: "AI Engineer & Full Stack Developer",
    description:
      "I design and build AI-powered products. Engineering student at Turin, Italy.",
  },
  social: {
    github: "https://github.com/therealthund3rr",
    email: "t.thund3rr@gmail.com",
    linkedin: "https://www.linkedin.com/in/nicol%C3%B2-celentano-7677413a4/",
    instagram: "https://www.instagram.com/nico.celentano_/",
  },
  about: {
    title: "About Me",
    description:
      "Engineering student at Turin. I've been building software tools since high school — first for myself, then for others. These days everything I build starts with a spec in Claude Code and ends with something that actually runs. My background is in video editing and content, but what excites me now is the overlap between design and engineering: making interfaces that are both beautiful and genuinely useful.",
  },
  career: [
    {
      period: "Now",
      title: "Computer Engineering",
      company: "Politecnico di Torino",
      desc: "Studying computer engineering. Learning the fundamentals — algorithms, systems, math — and applying them directly to personal projects.",
      type: "study" as const,
      bar: 65,
    },
    {
      period: "2026",
      title: "Mobile App Development",
      company: "Life OS — Personal Project",
      desc: "Built a full production mobile app with React Native and Expo. Learned: cross-platform animations with Lenis, Supabase real-time sync, AI-driven recommendation logic, and shipping something that actually runs on a phone.",
      type: "project" as const,
      bar: 85,
    },
    {
      period: "2026",
      title: "Web Development & APIs",
      company: "Command Center — Personal Project",
      desc: "Built a SaaS-style dashboard with Alpine.js and vanilla JS. Learned: SVG rendering from scratch, live finance API integration, localStorage state management, and making a dashboard look premium without a framework.",
      type: "project" as const,
      bar: 78,
    },
    {
      period: "2025–26",
      title: "Node.js & Automation",
      company: "Bots & Automations",
      desc: "Built WhatsApp bots and automation tools running 24/7 on Windows Task Scheduler. Learned: Node.js async flow, shutdown sequencing, WhatsApp API edge cases, and real-world deployment without cloud infrastructure.",
      type: "project" as const,
      bar: 70,
    },
    {
      period: "pre",
      title: "Video & Content Production",
      company: "Freelance",
      desc: "Years of video editing, YouTube production, and AI-assisted image generation. This is where the design eye comes from — color, pacing, composition. Still informs every UI decision.",
      type: "background" as const,
      bar: 60,
    },
  ],
  techStack: [
    { symbol: "Cc", name: "Claude Code", color: "#ff6b35", number: 1 },
    { symbol: "Re", name: "React", color: "#61dafb", number: 2 },
    { symbol: "Rn", name: "React Native", color: "#61dafb", number: 3 },
    { symbol: "Ts", name: "TypeScript", color: "#3178c6", number: 4 },
    { symbol: "Tj", name: "Three.js", color: "#ffffff", number: 5 },
    { symbol: "Gs", name: "GSAP", color: "#88ce02", number: 6 },
    { symbol: "Nj", name: "Node.js", color: "#339933", number: 7 },
    { symbol: "Py", name: "Python", color: "#ffd343", number: 8 },
    { symbol: "Sb", name: "Supabase", color: "#3ecf8e", number: 9 },
    { symbol: "Al", name: "Alpine.js", color: "#77c1d2", number: 10 },
    { symbol: "Js", name: "JavaScript", color: "#f7df1e", number: 11 },
    { symbol: "Vi", name: "Vite", color: "#646cff", number: 12 },
    { symbol: "Pe", name: "Prompt Eng.", color: "#0055ff", number: 13 },
    { symbol: "Ux", name: "UI/UX Design", color: "#ff61d2", number: 14 },
    { symbol: "Gh", name: "Git / GitHub", color: "#f05032", number: 15 },
    { symbol: "Ws", name: "WhatsApp Auto", color: "#25d366", number: 16 },
    { symbol: "Gp", name: "ChatGPT", color: "#74aa9c", number: 17 },
    { symbol: "Cu", name: "Cursor", color: "#ffffff", number: 18 },
    { symbol: "Ps", name: "Photoshop", color: "#31a8ff", number: 19 },
    { symbol: "Pr", name: "Premiere", color: "#9999ff", number: 20 },
  ],
  work: [
    {
      title: "Life OS",
      tech: "React Native · Expo · Supabase · Claude API",
      desc: "AI-first personal decision engine. The hard parts: smooth animations on mobile with Lenis, Supabase real-time sync without re-renders, and building a UI that feels native, not webview.",
      status: "active" as const,
      image: "/life-os-icon.png",
    },
    {
      title: "Command Center",
      tech: "Alpine.js · Supabase · Vanilla JS",
      desc: "Dashboard for the Life OS ecosystem. Bugs that taught me things: SVG namespace errors in donut charts, getScreenCTM hover issues, finance layout that kept breaking at edge cases.",
      status: "active" as const,
      icon: "dashboard",
    },
    {
      title: "Agenzia Locale",
      tech: "React · Cloudflare Pages · Node.js",
      desc: "Web agency template + business scraper for local SMBs. Learned: Google Places API rate limits, Cloudflare Workers cold start behavior, and how to pitch to people who've never heard of React.",
      status: "active" as const,
      icon: "agency",
    },
    {
      title: "Jarvis",
      tech: "Claude API · Node.js · MCP",
      desc: "Personal AI assistant with MCP integration and workflow automation. WIP — currently working on memory persistence across sessions and tool chaining.",
      status: "wip" as const,
      icon: "ai",
    },
    {
      title: "Waste Bot",
      tech: "Node.js · WhatsApp (open-wa)",
      desc: "WhatsApp bot that reminds the family when to take out specific recycling. Fixed: async sendText timing (3s delay) and shutdown sequencing so it doesn't corrupt state on Task Scheduler stop.",
      status: "shipped" as const,
      icon: "bot",
    },
  ],
  allowedDomains: ["localhost", "127.0.0.1", "therealthund3rr.github.io"],
};
